# Generated by Django 6.0 on 2025-12-28 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskdetail",
            name="assigned_to",
        ),
    ]
