# Generated by Django 6.0 on 2025-12-14 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="Project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.project",
            ),
        ),
    ]
